### ISSUE TITLE
  Nested component click event error

### ISSUE THREAD

**Issue by ys2rice2yangsong** [sycamore-rs/sycamore#655] opened 2024-01-11 01:29 UTC
**Describe the bug**

**To Reproduce**

#[component(inline_props)]
fn T<G:Html>(cx:Scope,title: String, level: i32) -> View<G> {
    let tt = title.clone();
    let tt_clone = title.clone();
    view!{
        cx,
        (
            if level<5 {
                view!{
                    cx,
                    div{
                        T(
                            title="afasdf".to_string(),
                            level=level+1
                        )
                    }
                }
            } else {
                view!{
                    cx,
                    p(
                    	on:click=move|e| {
                    		console!("asdfasdf".to_string());
                    	}
                    ){
                        (tt)
                    }
                }
            }
        )
    }
}

**Expected behavior**

**Screenshots**
error info:
Uncaught Error: closure invoked recursively or after being dropped

**Environment**

- Sycamore: [e.g. 0.8.2, master]
- Browser: [e.g. chrome, safari, if applicable]
- OS: [e.g. Windows, if applicable]

**Additional context**

**Comment by lukechu10** [comment] 2024-01-11 22:18
Duplicate of #654 and #433

**Closed by lukechu10** 2024-01-11 22:18 UTC
