### ISSUE TITLE
Do not implicitly call `.to_string()` in `view!`

### ISSUE THREAD

**Issue by jquesada2016** [sycamore-rs/sycamore#264] opened 2021-09-23 21:38 UTC
I was trying to use a bool attribute for an `<a>` tag as follows:

```rust
let link_text = "blah";
let download = false;

template! {
    a(download=download) { (link_text) }
}
```

And when I inspected the `DOM`, I noticed the `download` attribute was set to `"false"`. Looking at the `cargo expand` output, I noticed that all, but a few attributes, such as `required` were being treated specially.

I believe it might be a good idea to implement a trait such as the following (pseudo code):
```rust
trait AttributeKind {
    const fn is_bool() -> bool
}

impl AttributeKind for bool {
    const fn is_bool() -> bool { true }   // false for string
}
```

Which could then be used in a macro as follows:
```rust
/* inside of template! macro */
attribute!(value)
```

Which could expand to _something_ like:
```rust
if (value as AttributeKind)::is_bool() {
    /* add the required code to add/remove the attribute
} else {
    /* use the normal ToString trait */
{
```

This could work for all possible attributes and wouldn't have to be cherry-picked.

The trait could be only really have to be implemented for bool, returning `true`, and a blanket implementation for anything implementing ToString returning `false`.

**Comment by jquesada2016** [comment] 2021-09-23 22:02
On this note, accepting Option would also be a good idea, because when working with Web Components, many of their API's involve adding/removing attributes to toggle or set functionality. I don't currently see a way to toggle attributes without using the raw Template and GenericNode API's.

**Comment by lukechu10** [comment] 2021-09-25 04:27
According to the [spec](https://html.spec.whatwg.org/#attributes-3), download is a text attribute.
To set `download` without specifying a value, you can use the empty string slice (`""`).

I'm beginning to think that maybe it's not such a good idea to use the `ToString` trait for all types as it can result in somewhat unexpected behavior at times. It might be better to only allow `AsRef<str>` values.

**Comment by jquesada2016** [comment] 2021-09-25 14:10
I recommend checking out [Seed](https://github.com/seed-rs/seed) and how they go about this in their `HTML` macros. That's where I got the idea for adding an `IntoAttributes` trait. Ideally, one would have an `IntoAttribute` and an `IntoChild` (or whatever) for each respective part of the `template!`. Then one could implement it for the important types (`bool`, `&str`, etc.), and this would give complete predictability and better error reporting. The main blocker right now is the stabilization of `specialization`. Or we could use the `Any` trait if using `'static`...

**Comment by lukechu10** [comment] 2021-09-26 02:08
> Or we could use the `Any` trait if using `'static`...

That's not a blocker because the expression is moved into a static closure. Since specialization is not stabilized and doesn't appear to be any time soon, we'll probably just use the `Any` trait and downcasting.

**Comment by lukechu10** [comment] 2022-03-21 22:37
I'll be closing this now since I think the current solution of using the `ToString` trait works fine for now.

**Closed by lukechu10** 2022-03-21 22:37 UTC
Labels: enhancement, BREAKING CHANGE
