### ISSUE TITLE
InvalidStateError: `bind_ref`'ed element is not connected

### ISSUE THREAD

**Issue by Dragonink** [sycamore-rs/sycamore#467] opened 2022-08-17 11:28 UTC
### Describe the bug
I have a component which contains a `Keyed` component.
I use it in two different places: one as a normal child of a view, and another in a `Children`.
That `Children` object is a prop of a Dialog component, which is `bind_ref`'ed such that I can open it from a button.

The first component works fine when inserted as a normal child; but an error is thrown when I try to open the Dialog:
```
InvalidStateError: HTMLDialogElement.showModal: Dialog element is not connected
```

This error does **not** happen when I remove the signals from the component.

### Overview of my code
```rust
#[component]
fn Dialog<'a, G: Html>(cx: Scope<'a>, props: DialogProps<'a>) -> View<G> {
    dialog()
        .bind_ref(props.dialog_ref.clone())
        .c(props.children.call(cx))
        .view(cx)
}

#[component]
fn DialogChildren<G: Html>(cx: Scope) -> View<G> {
    let keyed_props = KeyedProps::builder()/* ... */.build();

    some_element().c(Keyed(cx, keyed_props)).view(cx)
}

#[component]
fn Main<G: Html>(cx: Scope) -> View<G> {
    let dialog_ref = create_node_ref(cx);
    let dialog_props = DialogProps::builder()
        .dialog_ref(dialog_ref)
        .children(Children::new(cx, |cx| {
            DialogChildren(cx)
        })
        .build();

    main()
        .c(DialogChildren(cx))
        .c(button().t("Open dialog").on("click", |_| {
            dialog_ref
                .get::<DomNode>()
                .unchecked_into::<HtmlDialogElement>()
                .show_modal()
                .unwrap(); // ERROR HAPPENS HERE
        })
        .c(Dialog(cx, dialog_props))
        .view(cx)
}
```

### Expected behavior
The Dialog should open normally.

### Environment
- Sycamore: `master`
- Browser: Firefox
- OS: Linux

**Comment by lukechu10** [comment] 2022-08-17 23:53
This is not an issue with sycamore but rather because the dialog seems to be already open. Here are the MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal#exceptions

I'll close this issue now but please feel free to reopen if your issue is not resolved.

**Comment by Dragonink** [comment] 2022-08-18 09:46
I know this error comes from the HTML element, but:
how can the dialog be already open when I just load the page, without the `open` attribute set and without the dialog being open in the UI?

Moreover the error does not happen when I remove the Signals from the DialogChildren.

**Comment by lukechu10** [comment] 2022-08-18 15:47
Do you get an error if you manually select the element in devtools and call `showModal` from the JS console?

**Comment by Dragonink** [comment] 2022-08-19 11:57
No, when I call `showModal` manually from the console the dialog shows up normally.

**Comment by lukechu10** [comment] 2022-08-19 15:54
Does the dialog open first than throws an error? or does it not show at all?

**Comment by Dragonink** [comment] 2022-08-19 18:10
The dialog immediately throws an error without showing up.

**Comment by lukechu10** [comment] 2022-08-20 00:05
Ok. I'll open this again to track this issue.

**Comment by lukechu10** [comment] 2024-09-09 15:33
Hey there, sorry for taking so long to get to this. I'm not able to reproduce this on the latest version of Sycamore. Since this issue is so old now, I'm going to close it since Sycamore's API has changed quite a bit already and also because I don't think this is an issue with Sycamore in the first place but rather with browser APIs.

If you have any more problems, could you please open a new issue? Thanks!

**Closed by lukechu10** 2024-09-09 15:33 UTC
Labels: C-bug, S-needs-mre
