### ISSUE TITLE
TodoMVC example doubles items when switching between All and Completed

### ISSUE THREAD

**Issue by UnlimitedCookies** [sycamore-rs/sycamore#427] opened 2022-05-27 13:17 UTC
**Describe the bug**
When you run the latest version of the TodoMVC example, add some items and then mark some as completed, then when you switch between the tabs All and Completed, the amount of  not completed items will double.

Further, when switching to the completed tab, also uncompleted items will show up. 

**To Reproduce**

1. Run TodoMVC example
2. Add items
3. Mark some as done
4. Switch between All and Completed

**Expected behavior**
I expect the amount of items not to double

**Screenshots**
![image](https://user-images.githubusercontent.com/49200216/170706762-d57c54cb-49ab-4a1f-ad8b-1248ddbcfb56.png)

**Environment**

- Sycamore: master
- Browser: Firefox 100.0-1
- OS: Arch Linux

**Comment by lukechu10** [comment] 2022-05-29 01:17
I can't reproduce this here: https://sycamore-rs.netlify.app/examples/todomvc/# Can you please try it out on your side?

**Comment by mc1098** [comment] 2022-05-29 18:19
In order to reproduce:
1. create any list of 3 or more items
2. mark the second item in the list as completed
3. switch to the 'completed' filter
    - notice the completed item at the start and any remaining items have stayed too.
4. switch back to the 'all' filter
    - notice that all the items after the completed item has been duplicated.

> I can't reproduce this here: https://sycamore-rs.netlify.app/examples/todomvc/# Can you please try it out on your side?

I can reproduce the above locally and using that link.

Notably, if only the first item is marked as completed then the bug doesn't occur and if the final item is marked as complete when the second item is then it doesn't occur; however, mark a middle item with any uncompleted items between it and the last and the effect will occur with those uncomplete items.

**Comment by lukechu10** [comment] 2022-05-29 18:56
hmm this is not good. This must be a regression somewhere because I don't believe there was this issue in previous versions of sycamore.

**Closed** 2022-05-30 21:57 UTC
Labels: bug, P-high
