### ISSUE TITLE
Updating a nested list can cause a panic

### ISSUE THREAD

**Issue by Vectornaut** [sycamore-rs/sycamore#744] opened 2024-11-01 04:45 UTC
Updating a nested list can cause a panic when the following conditions are both present:
- The inner list accesses the signal that the outer list iterates over.
- The update comes from within an event handler.

#### To Reproduce

Here's a [reproducing example](https://github.com/user-attachments/files/17596014/nested-list-panic.zip). As written, this code panics when you press the *Insert* button.

#### Expected behavior

You can see the expected behavior in the example by commenting out line 25. Since the inner list no longer accesses the signal that the outer list iterates over, the panic is prevented.

Since the example doesn't include any obviously panic-inducing code, I'd expect it to either run smoothly, fail to compile, or at least compile with a warning.

#### Environment

- Sycamore: 0.9.0-beta.4
- Browsers: Firefox 132.0 (64-bit) and Ungoogled Chromium 129.0.6668.100
- OS: Ubuntu 22.04

**Comment by lukechu10** [comment] 2024-11-01 10:00
I'm going to close this now as this is more to do with not so great error message which has been somewhat mitigated by #745. The problem is that you cannot access a signal from inside the `update(...)` function of another signal. The simple workaround is to simply split the read and update into two separate chunks:

```rust
let inner_signal = outer_signal.with(|outer| outer.list[123]);
inner_signal.update(...);
```

**Closed by lukechu10** 2024-11-01 10:00 UTC
Labels: C-bug

**Comment by Vectornaut** [comment] 2024-11-01 12:24
Thanks for improving the panic message! For some reason, I'm not seeing the new message when I rebuild the example code with
```
sycamore = { git = "https://github.com/sycamore-rs/sycamore" }
```

Trunk says that it's compiling Sycamore from `https://github.com/sycamore-rs/sycamore#fbe0d84a`, but the panic message I get on Firefox looks similar to the old one, and it doesn't contain the string "cannot read signal while updating". Am I using `console_error_panic_hook` wrong? I'm building and serving with `trunk serve`, with no option flags.
```
Uncaught RuntimeError: unreachable executed
sycamore-trial-6a11401801da174f_bg.wasm:455433:1
    __rust_start_panic http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:455433
    rust_panic http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:454841
    h33fe77d38d305ca3 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:323704
    h98de848d678bad07 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:365832
    h2bcfc60c3cf0a312 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:455353
    rust_begin_unwind http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:416534
    hde8b7aa66e2831e1 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:422183
    hacfbd4e0f8d6ca3b http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:405811
    hc50f2c1afdfcd6cf http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:384973
    h9018ee0955eba22f http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:273893
    h67fed5d32bd9095f http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:398816
    hfde792f747777e12 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:346663
    h7d938238a993d1d8 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:226972
    hf003312ef46c1336 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:441271
    sycamore_trial-bab6029c9e35c370.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h23d87c0b29fa9e2f http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438881
    sycamore_trial-bab6029c9e35c370.wasm.<F as sycamore_core::component::Component<(),V,()>>::create::hcf29e4a6d852bd63 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439151
    h82e84db9652e53f3 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:420298
    h9dfba24005e1916c http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:318441
    h6656ff3c6122cdc4 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:427477
    h97d3d7abe88f0a8c http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438773
    he6d6d79048520a87 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:418937
    h6708955bfd54cad1 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:373047
    h1fbd31b6dd403982 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:310402
    h7dd8664495fdceea http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:316973
    hf2416b9654655886 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:454212
    h765d391b8cbe78a3 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:42810
    sycamore_trial-bab6029c9e35c370.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hb4507314b6e31638 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439690
    h8a6b6bdd2af054fd http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:329885
    h964247cc7d6cf188 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:423591
    sycamore_trial-bab6029c9e35c370.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h9ff73996d9ad59fe http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439636
    hfb2e4e634f2d3940 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:318871
    hd391ea9aa47ad042 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:427617
    hf03d839d5ac3d8ad http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:422308
    h407f7d92cda4b414 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:218133
    sycamore_trial-bab6029c9e35c370.wasm.<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h84335017a3698b22 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:397234
    hf1bb7de1e7ad2f9b http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:405408
    h244dfdf96987f894 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:200934
    h2916f0d89f9fc2fe http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:54192
    h4fa66aa9a1aabeef http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:98297
    h4bf681d9cf23ee0d http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:280281
    h3e0087950da9879b http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:356444
    h630347ddd6bd0c9d http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:343107
    h3a9a2e38e0c78813 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:190990
    h4fc08bf0fe7a594a http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:353543
    hbf436e8e50143307 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:287111
    sycamore_trial-bab6029c9e35c370.wasm.<F as sycamore_web::events::EventHandler<E>>::call::hf24eda1842382ad4 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:433144
    h1644d3272fbada28 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:414925
    h11cd92c2838eb56a http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:335239
    h2f82335f52a05920 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:418861
    sycamore_trial-bab6029c9e35c370.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h51a46554c56b1f99 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:347416
    __wbg_adapter_16 http://localhost:8080/sycamore-trial-6a11401801da174f.js:211
    real http://localhost:8080/sycamore-trial-6a11401801da174f.js:196
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_4357f9b7b3826784 http://localhost:8080/sycamore-trial-6a11401801da174f.js:352
    handleError http://localhost:8080/sycamore-trial-6a11401801da174f.js:228
    __wbg_addEventListener_4357f9b7b3826784 http://localhost:8080/sycamore-trial-6a11401801da174f.js:350
    ha834fb5570395bd3 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:231330
    sycamore_trial-bab6029c9e35c370.wasm.<sycamore_web::node::dom_node::DomNode as sycamore_web::node::ViewHtmlNode>::set_event_handler::hd5ad2271fcdd5587 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:228743
    sycamore_trial-bab6029c9e35c370.wasm.<T as sycamore_web::attributes::SetAttribute>::set_event_handler::h968bc654c472dacb http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:381021
    h0cd008d01dbffc6f http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:338970
    h9b7c4409aa641567 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:286565
    h636f41cb1625f5ff http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:441219
    sycamore_trial-bab6029c9e35c370.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h612543066d9f96ad http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438935
    sycamore_trial-bab6029c9e35c370.wasm.<F as sycamore_core::component::Component<(),V,()>>::create::h46c522390baaf1a6 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439043
    h202ce76f624c1cbc http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:420449
    h88ef2868674d6354 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:318226
    h31080c17ff50edcc http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:427407
    h0d9ec5d32baf3591 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438719
    h95bb68be76dcb2c7 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:166571
    h3097717652722fbb http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:441167
    sycamore_trial-bab6029c9e35c370.wasm.core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he45291fa87589a52 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438989
    sycamore_trial-bab6029c9e35c370.wasm.<F as sycamore_core::component::Component<(),V,()>>::create::h585eba81a0f41943 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439097
    h4cb63aadf1b64419 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:420525
    h49a7978010a7633f http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:318011
    h797779f607d90c7c http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:427547
    had06044ababd4425 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:438827
    hbeaf99e6fc19eedf http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:217959
    h430f53fb75cabbdc http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:174810
    h2371938049f7a93e http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:434174
    ha69572fd179e2d62 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:333266
    h1a4d0cf196964fb9 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:339144
    h11d2a69bb36cd879 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:439794
    hf43fe9f6e95a76d7 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:319133
    he67c19aa1826c758 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:455374
    h801d4e57bab192f3 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:441583
    h20fee53668551d8d http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:442725
    h981fcff37305fb1b http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:379241
    h42f9dcdc67cc3d3b http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:306795
    h0c107e61179246a2 http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:375731
    main http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:453744
    wasm http://localhost:8080/sycamore-trial-6a11401801da174f_bg.wasm:454884
    __wbg_finalize_init http://localhost:8080/sycamore-trial-6a11401801da174f.js:419
    __wbg_init http://localhost:8080/sycamore-trial-6a11401801da174f.js:473
    AsyncFunctionNext self-hosted:800
    (Async: async)
    <anonymous> http://localhost:8080/:9
```

**Comment by lukechu10** [comment] 2024-11-03 00:28
> Trunk says that it's compiling Sycamore from `https://github.com/sycamore-rs/sycamore#fbe0d84a`, but the panic message I get on Firefox looks similar to the old one, and it doesn't contain the string "cannot read signal while updating". Am I using `console_error_panic_hook` wrong? I'm building and serving with `trunk serve`, with no option flags.

I'm pretty sure you haven't set up `console_error_panic_hook` properly. Make sure you're calling `console_error_panic_hook::set_once();` _before_ calling `sycamore::render`, usually at the very start of your `fn main()`.

What you're seeing right now is the generic panic message without the panic hook.

**Comment by Vectornaut** [comment] 2024-11-11 08:46
> I'm pretty sure you haven't set up `console_error_panic_hook` properly

That was the problem! I see the new message now.
